const mongoose = require('mongoose');

/**
 * A screening / technical / MCQ question attached to a Job (Feature 5/6).
 * Recruiters can add questions manually when posting a job, or have the AI
 * auto-generate them (marked `autoGenerated: true`). Questions are stored
 * in a separate collection so a job can have any number of them and so the
 * same question bank could later be reused across jobs.
 */
const jobQuestionSchema = new mongoose.Schema(
  {
    jobId: { type: mongoose.Schema.Types.ObjectId, ref: 'Job', required: true, index: true },
    // Question type drives how it's rendered in the apply questionnaire and
    // how it's scored.
    type: {
      type: String,
      enum: ['mcq', 'technical', 'screening'],
      default: 'mcq',
    },
    question: { type: String, required: true, trim: true, maxlength: 1000 },
    // MCQ options — only populated for type 'mcq'.
    options: [{ type: String, trim: true }],
    // Correct answer index (for MCQs) or model answer (technical/screening).
    // Stored so the recruiter dashboard can auto-score; candidates never
    // see this field in the apply payload.
    correctAnswer: { type: String, default: '' },
    correctOptionIndex: { type: Number, default: null },
    // Whether the AI generated this question (vs recruiter hand-written).
    autoGenerated: { type: Boolean, default: false },
    // 1-based order within the questionnaire.
    order: { type: Number, default: 1 },
  },
  { timestamps: true }
);

jobQuestionSchema.index({ jobId: 1, order: 1 });

module.exports = mongoose.model('JobQuestion', jobQuestionSchema);
