const { extractJSON } = require('./aiService');

/**
 * AI-generated screening MCQs (Feature 6).
 *
 * Given a job title / designation + skills, this asks the AI to produce a
 * bank of multiple-choice questions suitable for screening applicants.
 * Recruiters can then edit them before saving (the controller persists
 * them as JobQuestion docs with `autoGenerated: true`).
 */

const MCQ_SYSTEM_PROMPT = `You are a technical recruiter and assessment author. Given a job title and a list of skills/tech stack, generate a set of high-quality multiple-choice screening questions.

Return STRICT JSON with exactly this shape:
{
  "questions": [
    {
      "question": "the question text",
      "options": ["option A", "option B", "option C", "option D"],
      "correctOptionIndex": <0-3>,
      "type": "mcq",
      "explanation": "one-line explanation of the correct answer (optional)"
    }
  ]
}

Rules:
- Generate exactly the requested number of questions.
- Cover the specified skills/tech stack.
- Each question must have exactly 4 options.
- correctOptionIndex must be the index of the correct option.
- Mix fundamentals, practical/application-level, and a couple of tricky/edge questions.
- Do NOT include any text outside the JSON.`;

/**
 * Generates MCQs for a job.
 * @param {string} title - e.g. "React Developer"
 * @param {string[]} skills - e.g. ["React", "JavaScript", "Redux", "Node"]
 * @param {number} count - number of questions (default 10, max 20)
 * @param {string} focus - optional instruction (e.g. "focus on backend")
 * @returns {Promise<Array<{question, options, correctOptionIndex, type, explanation}>>}
 */
const generateMCQs = async ({ title, skills = [], count = 10, focus = '' }) => {
  const n = Math.max(1, Math.min(20, count));
  const skillText = skills.length ? skills.join(', ') : 'general role fundamentals';
  const focusText = focus ? `\nAdditional focus: ${focus}` : '';

  const result = await extractJSON(
    MCQ_SYSTEM_PROMPT,
    `Job title: ${title}\nSkills/Tech stack: ${skillText}\nNumber of questions: ${n}${focusText}`
  );

  const questions = (Array.isArray(result.questions) ? result.questions : []).map((q, i) => ({
    jobId: null, // filled by controller
    type: q.type || 'mcq',
    question: q.question,
    options: q.options || [],
    correctOptionIndex: q.correctOptionIndex,
    correctAnswer: q.options?.[q.correctOptionIndex] || '',
    autoGenerated: true,
    order: i + 1,
  }));

  return questions.slice(0, n);
};

module.exports = { generateMCQs };
