const asyncHandler = require('../utils/asyncHandler');
const ApiResponse = require('../utils/ApiResponse');
const ApiError = require('../utils/ApiError');
const JobQuestion = require('../models/JobQuestion');
const Job = require('../models/Job');
const { generateMCQs } = require('../services/mcqService');

/**
 * Feature 5 — recruiter adds questions (manual).
 * Feature 6 — AI auto-generates questions.
 */

/**
 * GET /api/v1/jobs/:jobId/questions
 * Public (used in the apply questionnaire). Excludes correct answers.
 */
const getJobQuestions = asyncHandler(async (req, res) => {
  const { jobId } = req.params;
  const job = await Job.findById(jobId);
  if (!job) throw ApiError.notFound('Job not found');

  const questions = await JobQuestion.find({ jobId })
    .select('-correctAnswer -correctOptionIndex')
    .sort('order')
    .lean();

  // For MCQs, options are shuffled-free: we keep original order but strip answer.
  return new ApiResponse(200, { questions, hasQuestionnaire: questions.length > 0 }, 'Questions fetched').send(res);
});

/**
 * POST /api/v1/companies/jobs/:jobId/questions
 * Recruiter adds a batch of questions (mcq/technical/screening) to a job.
 */
const addQuestions = asyncHandler(async (req, res) => {
  const { jobId } = req.params;
  const job = await Job.findOne({ _id: jobId, companyId: req.user._id });
  if (!job) throw ApiError.notFound('Job not found');

  const { questions } = req.body;
  if (!Array.isArray(questions) || questions.length === 0) {
    throw ApiError.badRequest('questions must be a non-empty array');
  }

  const existing = await JobQuestion.countDocuments({ jobId });
  const docs = questions.map((q, i) => ({
    jobId,
    type: q.type || 'mcq',
    question: q.question,
    options: q.options || [],
    correctAnswer: q.correctAnswer || (q.options && q.options[q.correctOptionIndex]) || '',
    correctOptionIndex: q.correctOptionIndex ?? (q.type === 'mcq' ? q.correctOptionIndex : null),
    autoGenerated: false,
    order: existing + i + 1,
  }));

  const saved = await JobQuestion.insertMany(docs);

  // Update the job's questionnaire summary fields.
  await Job.findByIdAndUpdate(jobId, {
    hasQuestionnaire: true,
    questionnaireCount: existing + saved.length,
  });

  return new ApiResponse(201, { questions: saved }, 'Questions added').send(res);
});

/**
 * PUT /api/v1/companies/jobs/questions/:questionId
 * Recruiter edits a single question.
 */
const updateQuestion = asyncHandler(async (req, res) => {
  const question = await JobQuestion.findById(req.params.questionId);
  if (!question) throw ApiError.notFound('Question not found');

  const job = await Job.findOne({ _id: question.jobId, companyId: req.user._id });
  if (!job) throw ApiError.forbidden('You do not own this job');

  const allowed = ['question', 'options', 'correctAnswer', 'correctOptionIndex', 'type', 'order'];
  allowed.forEach((f) => {
    if (req.body[f] !== undefined) question[f] = req.body[f];
  });
  await question.save();

  return new ApiResponse(200, { question }, 'Question updated').send(res);
});

/**
 * DELETE /api/v1/companies/jobs/questions/:questionId
 */
const deleteQuestion = asyncHandler(async (req, res) => {
  const question = await JobQuestion.findById(req.params.questionId);
  if (!question) throw ApiError.notFound('Question not found');

  const job = await Job.findOne({ _id: question.jobId, companyId: req.user._id });
  if (!job) throw ApiError.forbidden('You do not own this job');

  await question.deleteOne();
  const count = await JobQuestion.countDocuments({ jobId: question.jobId });
  await Job.findByIdAndUpdate(question.jobId, {
    hasQuestionnaire: count > 0,
    questionnaireCount: count,
  });

  return new ApiResponse(200, null, 'Question deleted').send(res);
});

/**
 * POST /api/v1/companies/jobs/:jobId/questions/generate
 * AI generates MCQs for a job based on its title/skills.
 * Body: { count?, focus? }
 */
const generateJobQuestions = asyncHandler(async (req, res) => {
  const { jobId } = req.params;
  const job = await Job.findOne({ _id: jobId, companyId: req.user._id });
  if (!job) throw ApiError.notFound('Job not found');

  const { count = 10, focus = '' } = req.body;

  const generated = await generateMCQs({
    title: job.title,
    skills: job.skills || [],
    count,
    focus,
  });

  const existing = await JobQuestion.countDocuments({ jobId });
  const docs = generated.map((q, i) => ({
    ...q,
    jobId,
    order: existing + i + 1,
  }));
  const saved = await JobQuestion.insertMany(docs);

  await Job.findByIdAndUpdate(jobId, {
    hasQuestionnaire: true,
    questionnaireCount: existing + saved.length,
  });

  return new ApiResponse(201, { questions: saved }, 'Questions generated').send(res);
});

/**
 * GET /api/v1/companies/jobs/:jobId/questions
 * Recruiter view (includes correct answers for scoring/review).
 */
const getCompanyJobQuestions = asyncHandler(async (req, res) => {
  const { jobId } = req.params;
  const job = await Job.findOne({ _id: jobId, companyId: req.user._id });
  if (!job) throw ApiError.notFound('Job not found');

  const questions = await JobQuestion.find({ jobId }).sort('order').lean();
  return new ApiResponse(200, { questions }, 'Questions fetched').send(res);
});

module.exports = {
  getJobQuestions,
  addQuestions,
  updateQuestion,
  deleteQuestion,
  generateJobQuestions,
  getCompanyJobQuestions,
};
